### ISSUE TITLE
Update Needed

### ISSUE THREAD

**Issue by tfhartmann** [hmsrc/rc.hms.harvard.edu#1]
We need to Update our site to include our new Staff :smile:

**Comment by alextruong** [comment]
I can grab this. We'll need titles, blurbs and pictures from @sjoeboo @jfmcdonald @raffaelepotami and @poudelhari so we can add them. Also need to remove Jimi as well.

**Comment by tfhartmann** [comment]
Thanks!

**Comment by tfhartmann** [comment]
Blurb and Pic for @sjoeboo 

>Config management, automation, and new infrastructure technologies,
also, computers!

<img width="378" alt="screen shot 2015-10-22 at 1 57 24 pm" src="https://cloud.githubusercontent.com/assets/1078704/11349296/7dd99cd0-91f9-11e5-95c2-f26aa80be020.png">

**Comment by tfhartmann** [comment]
:construction_worker:

**Comment by poudelhari** [comment]
Blurb and pic for @poudelhari
I assist  the HMS community in automation , cloud computing and anything with #DevOps in it .
![image](https://cloud.githubusercontent.com/assets/15240952/11483781/670cdaf6-9778-11e5-92fa-28d2e113c10d.jpg)

**Comment by botka** [comment]
Please set a deadline for this?  I am not sure getting pics from someone should be the blocker (if it is).

**Comment by botka** [comment]
Also, Tim mentioned some changes to the process for updating the site, have these been documented someplace or are we still in planning stages?

**Comment by tfhartmann** [comment]
I updated the existing docs in the wiki to reflect the move to GH. The other change, to serve the site itself from an s3 bucket, will require more doc updates and PR ( both to implement and to discuss) to go live - so still in planning :)

**Comment by tfhartmann** [comment]
@alextruong could you please deploy any updates you have by Friday, and if more are required create an issue on this repo with a description of what's missing.

**Comment by raffaelepotami** [comment]
Sorry I send the picture to Alex using HipChat.
![raffaele](https://cloud.githubusercontent.com/assets/15384722/11533316/fc77a0f8-98d6-11e5-916d-43e51e7c5f30.jpg)
For the phrase how about: 
"I help users running and optimizing their codes. I specialize in Matlab and programs parallelization"

**Comment by alextruong** [comment]
@tfhartmann sure, will do.
